package mpstools.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptIHasDeleteButton = createDescriptorForIHasDeleteButton();
  /*package*/ final ConceptDescriptor myConceptIToggleableEditor = createDescriptorForIToggleableEditor();
  /*package*/ final ConceptDescriptor myConceptIntlAlias = createDescriptorForIntlAlias();
  /*package*/ final ConceptDescriptor myConceptIntlLanguage = createDescriptorForIntlLanguage();
  /*package*/ final ConceptDescriptor myConceptLocalizedKeyword = createDescriptorForLocalizedKeyword();
  /*package*/ final ConceptDescriptor myConceptMPSEditor_DeleteButton = createDescriptorForMPSEditor_DeleteButton();
  /*package*/ final ConceptDescriptor myConceptTranslation = createDescriptorForTranslation();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptIHasDeleteButton, myConceptIToggleableEditor, myConceptIntlAlias, myConceptIntlLanguage, myConceptLocalizedKeyword, myConceptMPSEditor_DeleteButton, myConceptTranslation);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.IHasDeleteButton:
        return myConceptIHasDeleteButton;
      case LanguageConceptSwitch.IToggleableEditor:
        return myConceptIToggleableEditor;
      case LanguageConceptSwitch.IntlAlias:
        return myConceptIntlAlias;
      case LanguageConceptSwitch.IntlLanguage:
        return myConceptIntlLanguage;
      case LanguageConceptSwitch.LocalizedKeyword:
        return myConceptLocalizedKeyword;
      case LanguageConceptSwitch.MPSEditor_DeleteButton:
        return myConceptMPSEditor_DeleteButton;
      case LanguageConceptSwitch.Translation:
        return myConceptTranslation;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForIHasDeleteButton() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "IHasDeleteButton", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L);
    b.interface_();
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/3165459099594229409");
    b.aggregate("deleteButton", 0x2bedf8479e5786a3L).target(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a2L).optional(false).ordered(true).multiple(false).origin("3165459099594229411").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIToggleableEditor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "IToggleableEditor", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x133bf0310e6e97L);
    b.interface_();
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/5413927358721687");
    b.prop("expanded", 0x133bf0310e6e98L, "5413927358721688");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntlAlias() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "IntlAlias", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179cL);
    b.class_(false, false, false);
    b.parent(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a1L);
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/1460099219963582364");
    b.associate("conceptToLocalize", 0x144350812ec12644L).target(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL).optional(false).origin("1460099219963586116").done();
    b.aggregate("keywords", 0x144350812ec117a3L).target(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179dL).optional(true).ordered(true).multiple(true).origin("1460099219963582371").done();
    b.alias("intl_alias");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIntlLanguage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "IntlLanguage", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x3581a114cbea3e7bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/3855539866698399355");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLocalizedKeyword() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "LocalizedKeyword", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179dL);
    b.class_(false, false, false);
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/1460099219963582365");
    b.prop("keyword", 0x144350812ec117a0L, "1460099219963582368");
    b.associate("language", 0x3581a114cbed7a78L).target(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x3581a114cbea3e7bL).optional(false).origin("3855539866698611320").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMPSEditor_DeleteButton() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "MPSEditor_DeleteButton", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a2L);
    b.class_(false, false, false);
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/3165459099594229410");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTranslation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpstools", "Translation", 0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec117a8L);
    b.class_(false, false, true);
    b.origin("r:0d9657dd-d4ac-4b70-844d-3d44fc7dc23a(mpstools.structure)/1460099219963582376");
    b.associate("selectedLanguage", 0x77c134f2d5ccc234L).target(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x3581a114cbea3e7bL).optional(false).origin("8629236578592277044").done();
    b.aggregate("languages", 0x3581a114cbead4e1L).target(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x3581a114cbea3e7bL).optional(true).ordered(true).multiple(true).origin("3855539866698437857").done();
    b.aggregate("aliases", 0x144350812ec117a9L).target(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179cL).optional(true).ordered(true).multiple(true).origin("1460099219963582377").done();
    b.alias("translation");
    return b.create();
  }
}
