package mpstools.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0a = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt_a0a)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new IntlAlias_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new IntlLanguage_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new LocalizedKeyword_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new MPSEditor_DeleteButton_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Translation_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt_a0c = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0c.index(cncpt_a0c)) {
      case 0:
        if (true) {
          if ("mpstools.editor.LocalizeableAlias".equals(editorComponentId)) {
            return Collections.<ConceptEditorComponent>singletonList(new LocalizeableAlias());
          }
        }
        break;
      case 1:
        if (true) {
          if ("mpstools.editor.ToggleButton".equals(editorComponentId)) {
            return Collections.<ConceptEditorComponent>singletonList(new ToggleButton());
          }
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }

  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0e = concept;
    switch (index_xbvbvu_a0e.index(cncpt_a0e)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new LocalizedKeyword_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179cL), MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x3581a114cbea3e7bL), MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179dL), MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x2bedf8479e5786a2L), MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec117a8L)).seal();
  private static final ConceptSwitchIndex index_xbvbvu_a0c = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x133bf0310e6e97L)).seal();
  private static final ConceptSwitchIndex index_xbvbvu_a0e = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179dL)).seal();
}
