package mpstools.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorSettings;

public class FSS {
  public static int defaultSize() {
    return EditorSettings.getInstance().getFontSize();
  }
  public static int small() {
    return (int) (defaultSize() * 0.75);
  }
  public static int medium() {
    return defaultSize();
  }

  public static int medium_large() {
    return (int) (defaultSize() * 1.25);
  }

  public static int large() {
    return (int) (defaultSize() * 1.5);
  }
}
