package mpstools.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import javax.swing.JButton;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/*package*/ class ToggleButton_ComponentBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public ToggleButton_ComponentBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createJComponent_6lxvc3_a();
  }

  private EditorCell createJComponent_6lxvc3_a() {
    EditorCell editorCell = EditorCell_Component.createComponentCell(getEditorContext(), myNode, _QueryFunction_JComponent_6lxvc3_a0(), "_6lxvc3_a");
    editorCell.setCellId("JComponent_6lxvc3_a");
    return editorCell;
  }
  private JComponent _QueryFunction_JComponent_6lxvc3_a0() {
    JButton button = new JButton();
    // This is a workaround to get around the limitations of Runnable instances 
    // in regards to non-final objects 
    final StringBuilder buttonText = new StringBuilder();
    getEditorContext().getRepository().getModelAccess().runReadAction(new Runnable() {
      public void run() {
        if (SPropertyOperations.getBoolean(myNode, MetaAdapterFactory.getProperty(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x133bf0310e6e97L, 0x133bf0310e6e98L, "expanded"))) {
          buttonText.append("Collapse");
        } else {
          buttonText.append("Expand");
        }
      }
    });
    button.setText(buttonText.toString());
    button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent p0) {
        getEditorContext().getRepository().getModelAccess().executeCommand(new Runnable() {
          public void run() {
            if (SPropertyOperations.getBoolean(myNode, MetaAdapterFactory.getProperty(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x133bf0310e6e97L, 0x133bf0310e6e98L, "expanded"))) {
              SPropertyOperations.set(myNode, MetaAdapterFactory.getProperty(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x133bf0310e6e97L, 0x133bf0310e6e98L, "expanded"), "" + (false));
            } else {
              SPropertyOperations.set(myNode, MetaAdapterFactory.getProperty(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x133bf0310e6e97L, 0x133bf0310e6e98L, "expanded"), "" + (true));
            }
          }
        });
      }
    });
    return button;
  }
}
