package mpstools.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import mpstools.behavior.IntlLanguage__BehaviorDescriptor;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;

public final class deleteLanguage_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public deleteLanguage_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:4814e9df-b95d-4d95-aaf0-26791f9bf941(mpstools.intentions)", "4664674638740381603"));
  }
  @Override
  public String getPresentation() {
    return "deleteLanguage";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new deleteLanguage_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Delete This Language";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      IntlLanguage__BehaviorDescriptor.customDelete_id6cSWq1JoJeE.invoke(node, editorContext);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return deleteLanguage_Intention.this;
    }
  }
}
