package mpstools.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import mpstools.behavior.IntlLanguage__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;

public final class deleteReferencedLanguage_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public deleteReferencedLanguage_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:4814e9df-b95d-4d95-aaf0-26791f9bf941(mpstools.intentions)", "4664674638740389132"));
  }
  @Override
  public String getPresentation() {
    return "deleteReferencedLanguage";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new deleteReferencedLanguage_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Delete Referenced Language";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      IntlLanguage__BehaviorDescriptor.customDelete_id6cSWq1JoJeE.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0x69a000cb56db442fL, 0xa085a182111bac09L, 0x144350812ec1179dL, 0x3581a114cbed7a78L, "language")), editorContext);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return deleteReferencedLanguage_Intention.this;
    }
  }
}
